#Use este script para instalar todos os pacotes que utilizaremsos durante o curso

install.packages("mlbench")
install.packages("caret")
install.packages("rpart")
install.packages("e1071")
install.packages("Matrix")
install.packages("plyr")
install.packages("Amelia")
install.packages("corrplot")
install.packages("Hmisc")
install.packages("ggplot2")
install.packages("outliers")
install.packages("ROSE")
install.packages("DMwR")
install.packages("klaR")
install.packages("Boruta")
install.packages("randomForest")
install.packages("caretEnsemble")
install.packages("kernlab")